version: "3.9"

services:
    
# Postgres с примонтированным внешним каталогом для хранения данных. Чтобы при удалении контейнера данные оставались. 
# Необходимо указывать версию postgres в конфиге
    
  PostgresVol:
      image: postgres:16.2
      container_name: Postgres_Volume
      restart: always      
      command:
          - "postgres"
          - "-c"
          - "client_connection_check_interval=300s"
      volumes:
          - E:\docker\volumes\postgres:/var/lib/postgresql/data
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=my-pass~003
          - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
          - '5432:5432'
            
  PostgresKeepAlive:
      image: postgres
      container_name: Postgres_KeepAlive
      restart: always
      command:
          - "postgres"
          - "-c"
          - "client_connection_check_interval=300s"  # САМАЯ ВАЖНАЯ ОПЦИЯ, доступная с Postgres 14
          - "-c"
          - "tcp_user_timeout=0"
          - "-c"
          - "tcp_keepalives_idle=600"
          - "-c"
          - "tcp_keepalives_interval=60"
          - "-c"
          - "tcp_keepalives_count=5"      
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=my-pass~003
      ports:
          - '7432:5432'
  
  PgBouncer:
      image: bitnami/pgbouncer
      container_name: PgBouncer
      restart: always
      environment:
          - PGBOUNCER_POOL_MODE=session
          - PGBOUNCER_MIN_POOL_SIZE=5
          - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
          - PGBOUNCER_DATABASE="Zenit-Mobile"
          - PGBOUNCER_PORT=6432
          - PGBOUNCER_MAX_CLIENT_CONN=100
          - PGBOUNCER_MAX_DB_CONNECTIONS=100
          - PGBOUNCER_DEFAULT_POOL_SIZE=50
          - POSTGRESQL_HOST=postgres
          - POSTGRESQL_PORT=5432
          - POSTGRESQL_PASSWORD=my-pass~003
          - POSTGRESQL_DATABASE=Zenit-Mobile
      ports:
          - '6432:6432'